# This is a Docker Compose file to deploy docker image.
services:
  netflix-clone:
    image: netflix-clone:latest
    container_name: netflix-clone
    ports:
      - "8000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - netflix-network
