# This is a Docker Compose file to deploy docker image.
services:
  netflix-clone:
    image: netflix-clone:latest
    container_name: netflix-clone
    ports:
      - "8000:80"
    environment:
      - ENV=development
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
